version: '3.5'

services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
    network_mode: 'host'
  redis:
    image: redis:6.2-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_AOF_ENABLED=no
    ports:
      - '6379:6379'
    network_mode: 'host'
  api:
    image: hakansandikkaya/coin-calculator:1.0
    depends_on:
      - postgres
      - redis
    ports:
       - '8081:8081'
    network_mode: 'host'